# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build NestJS app

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: npm install, build, and test
      run: |
        npm i -g ts-node typescript
        npm install --ignore-optional
        ts-node gen-gql-types
        npm run build
