# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy NestJS app to Azure App Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: npm install, build, and test
      run: |
        npm i -g yarn ts-node typescript
        yarn
        ts-node gen-gql-types
        yarn build
      #  yarn run test
    # - name: Upload artifact for deployment job
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: node-app
    #     path: .
    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gql-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1a05e9ff522843e9bd820c5e4f1388c8 }}
        package: .
    

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #   - name: Download artifact from build job
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: node-app

  #   - name: 'Deploy to Azure Web App'
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'gql-api'
  #       slot-name: 'production'
  #       publish-profile: ${{ secrets.AzureAppService_PublishProfile_1a05e9ff522843e9bd820c5e4f1388c8 }}
  #       package: .